### ISSUE TITLE
为什么用插入元素插入的表格合并单元格会报错

### ISSUE THREAD

**Issue by 10jinzhi** [Hufe921/canvas-editor#308]
### version

0.9.53

### Steps to reproduce

```
function executeInsertTable(row: number, col: number) {
  let docinfo = instance.command.getValue();
  let colgroup = [];
  let colgroupunit = { width: (docinfo.width - 2 * docinfo.margins[1]) / col };
  let tdList = [];
  let tdListunit = { colspan: 1, rowspan: 1, value: [{ value: "" }] };
  for (let i = 0; i < col; i++) {
    colgroup.push(colgroupunit);
    tdList.push(tdListunit); }
  let trList = [];
  let trListunit = { height: 50, minHeight: 50, tdList };
  for (let i = 0; i < row; i++) {
    trList.push(trListunit); }
  let elementList: IElement = {
    value: "",
    type: ElementType.TABLE,
    colgroup,
    trList,
    borderType: TableBorder.ALL,
    height: row * 50,
    width: docinfo.width - 2 * docinfo.margins[1],  };
  instance.command.executeInsertElementList([elementList]);
  instance.command.executeForceUpdate();
  // instance.command.executeInsertTable(row, col);
}
```

### What is expected?

成功合并

### What is actually happening?

Uncaught runtime errors:
×
ERROR
Cannot read properties of undefined (reading 'value')
TypeError: Cannot read properties of undefined (reading 'value')
    at Draw.getTableElementList (webpack-internal:///./node_modules/@hufe921/canvas-editor/dist/canvas-editor.es.js:85:159279)
    at Draw.getElementList (webpack-internal:///./node_modules/@hufe921/canvas-editor/dist/canvas-editor.es.js:85:159444)
    at RangeManager.setRange (webpack-internal:///./node_modules/@hufe921/canvas-editor/dist/canvas-editor.es.js:85:31647)
    at CommandAdapt.mergeTableCell (webpack-internal:///./node_modules/@hufe921/canvas-editor/dist/canvas-editor.es.js:85:222215)
    at Object.callback (webpack-internal:///./node_modules/@hufe921/canvas-editor/dist/canvas-editor.es.js:85:249796)
    at menuItem.onclick (webpack-internal:///./node_modules/@hufe921/canvas-editor/dist/canvas-editor.es.js:85:254529)

### Any additional comments?

这样插入表格显示不出网格边框，但是撤销再恢复就显示出来了

**Comment by 10jinzhi** [comment]
希望插入表格方法添加表格行高设置

**Comment by Hufe921** [comment]
```javascript
function executeInsertTable(row: number, col: number) {
  let docinfo = instance.command.getValue(); // ！！！仅使用到配置属性，可以使用getOptions方法，避免性能问题
  let colgroup = [];
  let colgroupunit = { width: (docinfo.width - 2 * docinfo.margins[1]) / col };
  let tdList = [];
  let tdListunit = { colspan: 1, rowspan: 1, value: [{ value: "" }] };
  for (let i = 0; i < col; i++) {
    colgroup.push(colgroupunit);
    tdList.push(tdListunit); } // ！！！此处存在相同对象引用
  let trList = [];
  let trListunit = { height: 50, minHeight: 50, tdList };
  for (let i = 0; i < row; i++) {
    trList.push(trListunit); } // ！！！此处存在相同对象引用
  let elementList: IElement = {
    value: "",
    type: ElementType.TABLE,
    colgroup,
    trList,
    borderType: TableBorder.ALL,
    height: row * 50,
    width: docinfo.width - 2 * docinfo.margins[1],  };
  instance.command.executeInsertElementList([elementList]); // ！！！此处可以增加克隆方法，如：JSON.parse(JSON.stringify(elementList))
  instance.command.executeForceUpdate(); // ！！此处是多余代码
  // instance.command.executeInsertTable(row, col);
}
```
原因是：单元格对象指向相同引用，内部进行数据格式化时会存在值覆盖的问题
具体解决方法，查看注释

后续接口内部会增加克隆处理
